package com.wym.mapper;

import com.wym.model.BookDetail;
import com.wym.model.BookDetailExample.Criteria;
import com.wym.model.BookDetailExample.Criterion;
import com.wym.model.BookDetailExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class BookDetailSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String countByExample(BookDetailExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("bookdetail");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String deleteByExample(BookDetailExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("bookdetail");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String insertSelective(BookDetail record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("bookdetail");
        
        if (record.getBookid() != null) {
            sql.VALUES("bookid", "#{bookid,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeid() != null) {
            sql.VALUES("typeid", "#{typeid,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            sql.VALUES("avatar", "#{avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getDescri() != null) {
            sql.VALUES("descri", "#{descri,jdbcType=VARCHAR}");
        }
        
        if (record.getIsbn() != null) {
            sql.VALUES("isbn", "#{isbn,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=VARCHAR}");
        }
        
        if (record.getQuantity() != null) {
            sql.VALUES("quantity", "#{quantity,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicationtime() != null) {
            sql.VALUES("publicationtime", "#{publicationtime,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            sql.VALUES("author", "#{author,jdbcType=VARCHAR}");
        }
        
        if (record.getSoldout() != null) {
            sql.VALUES("soldout", "#{soldout,jdbcType=VARCHAR}");
        }
        
        if (record.getGlance() != null) {
            sql.VALUES("glance", "#{glance,jdbcType=VARCHAR}");
        }
        
        if (record.getBookname() != null) {
            sql.VALUES("bookname", "#{bookname,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String selectByExample(BookDetailExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("bookid");
        } else {
            sql.SELECT("bookid");
        }
        sql.SELECT("typeid");
        sql.SELECT("avatar");
        sql.SELECT("descri");
        sql.SELECT("isbn");
        sql.SELECT("price");
        sql.SELECT("quantity");
        sql.SELECT("publicationtime");
        sql.SELECT("author");
        sql.SELECT("soldout");
        sql.SELECT("glance");
        sql.SELECT("bookname");
        sql.FROM("bookdetail");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BookDetail record = (BookDetail) parameter.get("record");
        BookDetailExample example = (BookDetailExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("bookdetail");
        
        if (record.getBookid() != null) {
            sql.SET("bookid = #{record.bookid,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeid() != null) {
            sql.SET("typeid = #{record.typeid,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            sql.SET("avatar = #{record.avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getDescri() != null) {
            sql.SET("descri = #{record.descri,jdbcType=VARCHAR}");
        }
        
        if (record.getIsbn() != null) {
            sql.SET("isbn = #{record.isbn,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        }
        
        if (record.getQuantity() != null) {
            sql.SET("quantity = #{record.quantity,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicationtime() != null) {
            sql.SET("publicationtime = #{record.publicationtime,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        }
        
        if (record.getSoldout() != null) {
            sql.SET("soldout = #{record.soldout,jdbcType=VARCHAR}");
        }
        
        if (record.getGlance() != null) {
            sql.SET("glance = #{record.glance,jdbcType=VARCHAR}");
        }
        
        if (record.getBookname() != null) {
            sql.SET("bookname = #{record.bookname,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("bookdetail");
        
        sql.SET("bookid = #{record.bookid,jdbcType=VARCHAR}");
        sql.SET("typeid = #{record.typeid,jdbcType=VARCHAR}");
        sql.SET("avatar = #{record.avatar,jdbcType=VARCHAR}");
        sql.SET("descri = #{record.descri,jdbcType=VARCHAR}");
        sql.SET("isbn = #{record.isbn,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        sql.SET("quantity = #{record.quantity,jdbcType=VARCHAR}");
        sql.SET("publicationtime = #{record.publicationtime,jdbcType=VARCHAR}");
        sql.SET("author = #{record.author,jdbcType=VARCHAR}");
        sql.SET("soldout = #{record.soldout,jdbcType=VARCHAR}");
        sql.SET("glance = #{record.glance,jdbcType=VARCHAR}");
        sql.SET("bookname = #{record.bookname,jdbcType=VARCHAR}");
        
        BookDetailExample example = (BookDetailExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    public String updateByPrimaryKeySelective(BookDetail record) {
        SQL sql = new SQL();
        sql.UPDATE("bookdetail");
        
        if (record.getTypeid() != null) {
            sql.SET("typeid = #{typeid,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            sql.SET("avatar = #{avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getDescri() != null) {
            sql.SET("descri = #{descri,jdbcType=VARCHAR}");
        }
        
        if (record.getIsbn() != null) {
            sql.SET("isbn = #{isbn,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=VARCHAR}");
        }
        
        if (record.getQuantity() != null) {
            sql.SET("quantity = #{quantity,jdbcType=VARCHAR}");
        }
        
        if (record.getPublicationtime() != null) {
            sql.SET("publicationtime = #{publicationtime,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthor() != null) {
            sql.SET("author = #{author,jdbcType=VARCHAR}");
        }
        
        if (record.getSoldout() != null) {
            sql.SET("soldout = #{soldout,jdbcType=VARCHAR}");
        }
        
        if (record.getGlance() != null) {
            sql.SET("glance = #{glance,jdbcType=VARCHAR}");
        }
        
        if (record.getBookname() != null) {
            sql.SET("bookname = #{bookname,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("bookid = #{bookid,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bookdetail
     *
     * @mbg.generated Fri Mar 22 19:47:18 CST 2019
     */
    protected void applyWhere(SQL sql, BookDetailExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}