package com.wym.mapper;

import com.wym.model.Orders;
import com.wym.model.OrdersExample;
import com.wym.model.OrdersKey;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @SelectProvider(type=OrdersSqlProvider.class, method="countByExample")
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @DeleteProvider(type=OrdersSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @Delete({
        "delete from orders",
        "where orderid = #{orderid,jdbcType=VARCHAR}",
          "and cartid = #{cartid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(OrdersKey key);

    @Delete({
            "delete from orders",
            "where orderid = #{orderid,jdbcType=VARCHAR}"
    })
    int deleteOrder(String orderid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @Insert({
        "insert into orders (orderid, cartid, ",
        "username)",
        "values (#{orderid,jdbcType=VARCHAR}, #{cartid,jdbcType=VARCHAR}, ",
        "#{username,jdbcType=VARCHAR})"
    })
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @InsertProvider(type=OrdersSqlProvider.class, method="insertSelective")
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @SelectProvider(type=OrdersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="orderid", property="orderid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="cartid", property="cartid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR)
    })
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @Select({
        "select",
        "orderid, cartid, username",
        "from orders",
        "where orderid = #{orderid,jdbcType=VARCHAR}",
          "and cartid = #{cartid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="orderid", property="orderid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="cartid", property="cartid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR)
    })
    Orders selectByPrimaryKey(OrdersKey key);

    @Select({
            "select",
            "orderid, cartid, username",
            "from orders",
            "where orderid = #{orderid,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="orderid", property="orderid", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="cartid", property="cartid", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR)
    })
    List<Orders> queryByPrimaryKey(String orderid);

    @Select({
            "select",
            "orderid, cartid, username",
            "from orders",
            "where username = #{username,jdbcType=VARCHAR} order by orderid desc"
    })
    @Results({
            @Result(column="orderid", property="orderid", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="cartid", property="cartid", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR)
    })
    List<Orders> queryByName(String username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @UpdateProvider(type=OrdersSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Mar 19 12:15:33 CST 2019
     */
    @Update({
        "update orders",
        "set username = #{username,jdbcType=VARCHAR}",
        "where orderid = #{orderid,jdbcType=VARCHAR}",
          "and cartid = #{cartid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Orders record);
}